name: wear_ongoing_activity
description: Create and maintain ongoing activity notifications on Wear OS
version: 0.1.4+1
homepage: https://github.com/Rexios80/wear_ongoing_activity

environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  rexios_lints: ^6.0.1

  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.rexios.wear_ongoing_activity
        pluginClass: WearOngoingActivityPlugin
